# -*- coding: utf-8 -*-
"""avanzadas_programa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16yjvKa-xsjAiW_FrxMShOYEAk8lSCQG7
"""

import numpy as np
import matplotlib.pyplot as plt
import math


def f(x, y):
    return np.cos(x) * np.sin(y) - x / (y**2 + 1)


def grad_f(x, y):
    df_dx = -np.sin(x) * np.sin(y) - 1/(y**2 + 1)
    df_dy = np.cos(x) * np.cos(y) + (2 * x * y)/(y**2 + 1)**2
    return np.array([df_dx, df_dy])


def hess_f(x, y):
    d2f_dx2 = -np.cos(x) * np.sin(y)
    d2f_dy2 = -np.cos(x) * np.sin(y) - (2 * x * (3 * y**2 - 1))/(y**2 + 1)**3
    d2f_dxdy = -np.sin(x) * np.cos(y) + (2 * y)/(y**2 + 1)**2
    return np.array([[d2f_dx2, d2f_dxdy], [d2f_dxdy, d2f_dy2]])


def backtracking(f, grad_f, xk, pk, alpha0, rho=0.5, mu=1e-4):
    alpha = alpha0
    phi0 = f(xk[0], xk[1])
    grad_xk = grad_f(xk[0], xk[1])
    phi = np.dot(grad_xk, pk)

    while f(xk[0] + alpha * pk[0], xk[1] + alpha * pk[1]) > phi0 + mu * alpha * phi:
        alpha = rho * alpha

    return alpha

def gradiente_descendente(f, grad_f, x0, alpha, tol=1e-6, max_iter=1000):
    decimales = -int(math.log10(tol) + 1)

    xk = np.array(x0, dtype=float)
    tabla = []

    for k in range(max_iter):
        gxk = grad_f(*xk)
        norm_gxk = np.linalg.norm(gxk)
        pk = -gxk

        if norm_gxk < tol:
            break

        alpha_k = backtracking(f, grad_f, xk, pk, alpha)
        xk = xk + alpha_k * pk

        tabla.append({
            'iteracion': k,
            'xk': np.round(xk.copy(), decimales),
            'gradiente': np.round(gxk.copy(), decimales),
            'pk': np.round(pk.copy(), decimales),
            'norma_gradiente': round(norm_gxk, decimales),
            'alpha': round(alpha_k, decimales)
        })

    return xk, tabla


def newton(f, grad_f, hess_f, x0, tol=1e-6, max_iter=100):
    decimales = -int(math.log10(tol) + 1)

    xk = np.array(x0, dtype=float)
    tabla = []

    for k in range(max_iter):
        gxk = grad_f(*xk)
        norm_gxk = np.linalg.norm(gxk)

        if norm_gxk < tol:
            break

        H = hess_f(*xk)
        autovalores = np.linalg.eigvals(H)

        if np.min(autovalores) > 1e-8:
            pk = -np.linalg.solve(H, gxk)
        else:
            pk = -gxk

        alpha = 1.0
        for _ in range(20):
            x_new = xk + alpha * pk
            if f(*x_new) < f(*xk) + 1e-4 * alpha * np.dot(gxk, pk):
                break
            alpha *= 0.5

        xk = xk + alpha * pk

        tabla.append({
            'iteracion': k,
            'xk': np.round(xk.copy(), decimales),
            'gradiente': np.round(gxk.copy(), decimales),
            'pk': np.round(pk.copy(), decimales),
            'norma_gradiente': round(norm_gxk, decimales),
            'alpha': round(alpha, decimales)
        })

    return xk, tabla


def cuasi_newton_bfgs(f, grad_f, x0, tol=1e-6, nIter=100):
    decimales = -int(math.log10(tol) + 1)

    xk = np.array(x0, dtype=float)
    n = len(xk)
    Bk = np.eye(n)
    tabla = []

    for k in range(nIter):
        gxk = grad_f(*xk)
        norm_gxk = np.linalg.norm(gxk)

        if norm_gxk < tol:
            tabla.append({
                'iteracion': k,
                'xk': np.round(xk.copy(), decimales),
                'gradiente': np.round(gxk.copy(), decimales),
                'pk': None,
                'norma_gradiente': round(norm_gxk, decimales),
                'alpha': None
            })
            break

        pk = -Bk.dot(gxk)
        alpha = backtracking(f, grad_f, xk, pk, 1.0)

        xk_new = xk + alpha * pk

        sk = (xk_new - xk).reshape(-1, 1)
        yk = (grad_f(*xk_new) - gxk).reshape(-1, 1)

        sk_yk = float(sk.T @ yk)
        if abs(sk_yk) < 1e-10:
            sk_yk = 1e-10

        Bk = Bk + ((1 + (yk.T @ Bk @ yk) / sk_yk) * (sk @ sk.T)) / sk_yk \
             - (sk @ (yk.T @ Bk)) / sk_yk \
             - ((Bk @ yk) @ sk.T) / sk_yk

        tabla.append({
            'iteracion': k,
            'xk': np.round(xk.copy(), decimales),
            'gradiente': np.round(gxk.copy(), decimales),
            'pk': np.round(pk.copy(), decimales),
            'norma_gradiente': round(norm_gxk, decimales),
            'alpha': round(alpha, decimales)
        })

        xk = xk_new

    return xk, tabla


def powell_conjugate_directions_robusto(f, x0, tol=1e-6, max_iter=100):
    from scipy.optimize import minimize_scalar

    decimales = -int(math.log10(tol) + 1)

    X = np.array(x0, dtype=float)
    n = len(X)
    S = [np.eye(n)[i] for i in range(n)]

    tabla = []

    for k in range(max_iter):
        X_inicial = X.copy()

        for i in range(n):
            d = S[i]
            res = minimize_scalar(lambda a: f(*(X + a * d)), bounds=(-2, 2), method='bounded')
            alpha_i = res.x
            X = X + alpha_i * d

        S_conj = X - X_inicial
        norm_conj = np.linalg.norm(S_conj)

        if norm_conj < tol:
            break

        gxk = grad_f(X[0], X[1])

        tabla.append({
            'iteracion': k,
            'xk': np.round(X.copy(), decimales),
            'gradiente': np.round(gxk.copy(), decimales),
            'pk': np.round(S_conj.copy(), decimales),
            'norma_gradiente': round(np.linalg.norm(gxk), decimales),
            'alpha': None
        })

        for i in range(n - 1):
            S[i] = S[i + 1]
        S[-1] = S_conj / norm_conj

        if np.linalg.norm(X - X_inicial) < tol:
            break

    return X, tabla